### ISSUE TITLE
Review by coding partner

### ISSUE THREAD

**Issue by muskan2532150** [muskan2532150/PORTFOLIO#7]

**Comment by suzi216** [comment]
You have done a nice job till now. Your code is structured well and the code is very clear. One very small suggestion would be to make your cards a bit bigger in height.

**Comment by altontonn** [comment]
Good job on the desktop and mobile version, however, use Figma's image for the desktop and mobile version when adding an image to your portfolio.

**Comment by aceDavon** [comment]
I must commend your work so far, it is well structured and elegant. You might just want to make sure your images are a bit bigger in height.
